main: Chrome UI Testes

on:
  workflow_dispatch:

jobs:
  
  chrome-ui-tests:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - usues: actions/checkout@v3
      
      - name: List files project
      run: ls -l
