name: Chrome UI Tests

on:
  workflow_dispatch:

jobs:
  
 chrome-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2   
      
      - name: rodar lista de diretorio
        run: ls -l  
        
      
    
      
